### ISSUE TITLE
Restarting with external database configured re-runs the database init scripts

### ISSUE THREAD

**Issue by davosian** [spring-petclinic/spring-petclinic-rest#182]
When starting the application with the following docker-compose definition, restarting the application fails because it is trying to initialize the (then existing) database again:

```yaml
services:
  backend:
    image: springcommunity/spring-petclinic-rest:3.2.1
    ports:
      - "9966:9966"
    environment:
      SPRING_PROFILES_ACTIVE: postgres,spring-data-jpa
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: petclinic
      POSTGRES_USER: petclinic
      POSTGRES_PASSWORD: petclinic
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
```

Is this a bug or is there a way for the application to detect that the database has been initialized already?

When adding `SPRING_SQL_INIT_MODE: never` after the first run, the application works fine since this forces the application to skip the database initialization.
