### ISSUE TITLE
ID is required

### ISSUE THREAD

**Issue by Jingli2017** [spring-petclinic/spring-petclinic-rest#34]
Help, 
I did a lot of research but I cannot find where u put the id and birthday is required in requestbody in the pet post methid.

**Comment by arey** [comment]
Hi @Jingli2017 dit you finally find your answer?
Regarding the new `api-docs.yml` file, the `birthDate` of the pet should be submit in the `birthDate`field:
```
PetFields:
      title: Pet fields
      description: Editable fields of a pet.
      type: object
      properties:
        name:
          title: Name
          description: The name of the pet.
          type: string
          maxLength: 30
          example: Leo
        birthDate:
          title: Birth date
          description: The date of birth of the pet.
          type: string
          format: date
          example: '2010-09-07'
```
Please reopen if you have other questions.
